### ISSUE TITLE
音乐播放不了？

### ISSUE THREAD

**Issue by 78226415** [dueros/dcs-sdk-java#1]
你好：
       我把整个sdk下载后，按照DCS SDK（Java）开发者指南进行配置，对话和唤醒都没问题，当问到：播放刘若英的歌，收到的回答是：我听快乐男声唱的，没有歌曲播放，这是怎么回事呢？

谢谢

**Comment by haoxunwang** [comment]
同问，也得到了相同的结果，播放不了音乐，是操作不对吗？建议：md说明文档中的图片，可以加个width参数调解下图片大小，影响阅读。

**Comment by 78226415** [comment]
我进行调试了一下，当说完：播放刘若英的歌，得到3个回复命令，第一个是StopListen，第二个是Speak，第三个是HtmlView，第二个应该是“我听快乐男声唱的”的音频，第三个应该是显示“我听快乐男声唱的”这个回复，没发现有播放MP3的回复命令呀

**Comment by Panxiaozhu** [comment]
请问怎么集成到自己的项目里？

**Comment by 78226415** [comment]
现在还没集成，只是先研究一下看看怎么用

**Comment by ta893115871** [comment]
1. 可能有2歌问题造成的。一是后台默认没有打开音乐服务，由于音乐资源正在升级中，音乐服务暂不可用，预计 下周 新版的音乐服务 将会开发完成并上线。

2.如果是android 6.0以上可能互有问题，可以修改MediaPlayerImpl.java的444行，改为：
  if (currentSeekMilliseconds > 0) {
                seekTo(currentSeekMilliseconds);
            } else {
                mp.start();
            }

**Comment by 78226415** [comment]
按照2的改法，可以播放了，谢谢

**Comment by Sdcxv** [comment]
@ta893115871 在Android Things上部署后点击授权页面时`com.baidu.duer.dcs.androidsystemimpl.webview.BaseWebView`在初始化时候执行到第62行`super(context);`时会提示`WebViewFactory: Chromium WebView package does not exist`然后闪退。

**Comment by ta893115871** [comment]
Android Things上难道没有WebView？

**Comment by Sdcxv** [comment]
@ta893115871 有webview，但是版本似乎有点特殊，版本号是0.0.1。试着安装play版本的apk，签名冲突，又无法卸载自带版本。
