### ISSUE TITLE
问：今天天气是什么，默认是北京。这个能根据定位来回答吗

### ISSUE THREAD

**Issue by DituLin** [dueros/dcs-sdk-java#10]

**Comment by IMUDGES-YY** [comment]
可以查看应用的权限，此应用是没有定位权限的，所以应该是不可以

**Comment by DituLin** [comment]
我看到 WebView 里有启用定位 ，但是并没有用

**Comment by zy1101** [comment]
我之前注册的账号没有通过审核之前   询问天气播报的也是北京  现在审核通过  播报的就是你当前位置的天气  我也不知道是不是这个原因   你可以试试

**Comment by IMUDGES-YY** [comment]
审核是指DuerOS开放平台的审核吗？不应该是审核之后创建新的产品，然后才能用自己的client_id使用这个demo吗？

**Comment by zy1101** [comment]
我在没审核之前就可以创建应用，具体网址 http://developer.dueros.baidu.com/openduer/product/getproduct
，但是我试了在
配置DuerOS下游服务里面的“聊天定制”里面启用的那些功能都用不了，审核过了就可以使用

**Comment by ATeamMac2014** [comment]
定位信息需要开发者传入，下个版本会有

**Comment by IMUDGES-YY** [comment]
请问传入至什么地方，能详细说一下吗？

**Comment by Tracy6465** [comment]
应该是根据ip地址来定位的

**Comment by zhangyan063hf** [comment]
key


默认的可以传输经纬度信息后 就能自动识别地理位置



在 2017-12-15 17:12:47，"Chris AuYeung" <notifications@github.com> 写道：


应该是根据ip地址来定位的
