### ISSUE TITLE
关于掉线问题（可能是）

### ISSUE THREAD

**Issue by IMUDGES-YY** [dueros/dcs-sdk-java#14]
今天测试之前的demo，刚启动应用的时候可以成功进行语音交互，但如果我在几分钟（甚至一分钟不到）内没有连续的发出语音指令，然后再重新发送语音指令时，demo不会有任何响应（可以使用唤醒词唤醒，当然这时在本地做的）。
在Debug过程中也发现，服务器没有回传任何数据，请问这是什么原因？是本地的原因吗？

**Comment by ATeamMac2014** [comment]
请github上最新版本，已经修复

**Comment by ATeamMac2014** [comment]
请更新最新版本

**Comment by ATeamMac2014** [comment]
已经解决， 请更新最新版本
