### ISSUE TITLE
sample登录失败啊~

### ISSUE THREAD

**Issue by CSDgod** [dueros/dcs-sdk-java#6]
![s70718-130525](https://user-images.githubusercontent.com/14586630/28301538-ecd7ebb4-6bb9-11e7-9ff4-3d72ea4b67df.jpg)

**Comment by ta893115871** [comment]
可以看下readme的前置条件的b项

**Comment by CSDgod** [comment]
@ta893115871  我用默认的redirect_uri=oob 到了默认的授权回调页了OAuth2.0，然后怎么去到语音输入界面？

**Comment by ta893115871** [comment]
@CSDgod   登录成功就可以进去了

**Comment by CSDgod** [comment]
@ta893115871  ![s70718-140251](https://user-images.githubusercontent.com/14586630/28302760-e37298dc-6bc1-11e7-809b-0c48ae4b4f97.jpg)
就到OAuth2.0 没进语音输入界面。

**Comment by CSDgod** [comment]
@ta893115871 有官方QQ群什么的么，方便讨论

**Comment by ta893115871** [comment]
@CSDgod 群号:604592023
